version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: gerador_grafico
      POSTGRES_USER: gerador
      POSTGRES_PASSWORD: gerador01
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:  
  postgres_data: