# Generated by Django 5.1.4 on 2024-12-20 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('sucesso', 'Sucesso'), ('erro', 'Erro')], max_length=7, null=True)),
                ('entregue_em', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
            options={
                'db_table': 'mensagens',
            },
        ),
    ]
